on:
  push:
    branches-ignore:
      - master
      - "renovate/*"
      - "dependabot/*"
  workflow_dispatch:
name: Build
jobs:
  snapshot:
    strategy:
      fail-fast: false
      matrix:
        loader: [ forge, fabric ]
        release-task: [ discordupload ]
    #if: ${{!startsWith(github.ref.split(’/’)[2], 'release-please')}}
    runs-on: ubuntu-latest
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
# This is only needed if we need to run datagen
#      - name: Download MC assets
#        run: ./gradlew downloadAssets || ./gradlew downloadAssets || (sleep 30s && ./gradlew downloadAssets)
#      - name: Run DataGen
#        run: ./gradlew runData
      - name: Build and upload preview (run for non-release builds)
        if: ${{ github.ref }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Build
          ./gradlew :${{ matrix.loader }}:build :${{ matrix.loader }}:${{ matrix.release-task }}
